# Author: Yingding Wang
# Docker Compose file version 3.8
version: "3.8"
services:
  mongodb-3.6x:
    image: "mongo:3.6.21"
    container_name: 'db-mongodb-3.6x'
    ports:
      - "27017:27017"
    environment:
      # provide your credentials here, ${MY_INTDB_ROOT_USERNAME} is a env variable can be sett in .env file
      # this env setting will add a root user in the admin db with role {role: root, db: admin}
      - MONGO_INITDB_DATABASE=${MY_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MY_INITDB_ROOT_USERNAME} # database root user name
      - MONGO_INITDB_ROOT_PASSWORD=${MY_INITDB_ROOT_PASSWORD} # database root password
    volumes: # https://docs.docker.com/compose/compose-file/#volumes
      - type: bind
        source: "${MY_VOLUMES_PWD}/data/configdb"
        target: "/data/configdb"
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: "${MY_VOLUMES_PWD}/data/db"
        target: "/data/db"
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: "./init-mongo.js"
        target: "/docker-entrypoint-initdb.d/init-mongo.js" # this will be called during the first init
        read_only: true
        volume:
          nocopy: true
    networks:
      - mongodb-net # which is already created

# declarations
#volumes:
#  myconfigdb:
#    name: mongodb-3.6x-configdb
#    external: true
#  mydb:
#    name: mongodb-3.6x-db
#    external: true

networks:
  mongodb-net: # project-bridge
    name: mongodb-net
    driver: bridge


